### ISSUE TITLE
MailCatcher not working with SwagNewsletter Plugin

### ISSUE THREAD

**Issue by arturmeinzer** [shyim/ShyimMailCatcher#10]
### PHP Version

8.1

### Shopware Version

5.7

### Actual behaviour

MailCatcher is not working with SwagNewsletter Plugin.
`Fatal error: Uncaught TypeError: SwagNewsletter\Subscriber\MailTransport::__construct(): Argument #3 ($mailTransport) must be of type Shopware\Components\DependencyInjection\Bridge\MailTransport, FroshMailCatcher\Components\MailFactory given, called in /var/www/html/public/var/cache/dev_fef1e05141adf0a78c8d792b9d142056a0da8beb/proxies/ShopwareDev7700a37c85af5ddc03f07b752e21bff6d4fb8e8fDebugProjectContainer.php on line 18747 and defined in /var/www/html/public/custom/project/SwagNewsletter/Subscriber/MailTransport.php:72 Stack trace: #0 /var/www/html/public/var/cache/dev_fef1e05141adf0a78c8d792b9d142056a0da8beb/proxies/ShopwareDev7700a37c85af5ddc03f07b752e21bff6d4fb8e8fDebugProjectContainer.php(18747): SwagNewsletter\Subscriber\MailTransport->__construct() #1 /var/www/html/public/vendor/symfony/dependency-injection/Container.php(257): ShopwareDev7700a37c85af5ddc03f07b752e21bff6d4fb8e8fDebugProjectContainer->getSwagNewsletter_Subscriber_MailTransportService() #2 /var/www/html/public/vendor/symfony/dependency-injection/Container.php(231): Symfony\Component\DependencyInjection\Container->make() #3 /var/www/html/public/vendor/shopware/shopware/engine/Shopware/Components/DependencyInjection/Container.php(212): Symfony\Component\DependencyInjection\Container->get() #4 /var/www/html/public/vendor/shopware/shopware/engine/Shopware/Components/DependencyInjection/Container.php(136): Shopware\Components\DependencyInjection\Container->doLoad() #5 /var/www/html/public/vendor/shopware/shopware/engine/Shopware/Components/ContainerAwareEventManager.php(209): Shopware\Components\DependencyInjection\Container->get() #6 /var/www/html/public/vendor/shopware/shopware/engine/Shopware/Components/ContainerAwareEventManager.php(143): Shopware\Components\ContainerAwareEventManager->lazyLoad() #7 /var/www/html/public/custom/plugins/FroshProfiler/Components/Event/EventManager.php(294): Shopware\Components\ContainerAwareEventManager->getListeners() #8 /var/www/html/public/custom/plugins/FroshProfiler/Components/Event/EventManager.php(84): FroshProfiler\Components\Event\EventManager->parentNotify() #9 /var/www/html/public/vendor/shopware/shopware/engine/Library/Enlight/Components/Mail.php(392): FroshProfiler\Components\Event\EventManager->notify() #10 /var/www/html/public/vendor/shopware/shopware/engine/Shopware/Controllers/Frontend/Account.php(557): Enlight_Components_Mail->send() #11 /var/www/html/public/vendor/shopware/shopware/engine/Shopware/Controllers/Frontend/Account.php(468): Shopware_Controllers_Frontend_Account->sendResetPasswordConfirmationMail() #12 /var/www/html/public/vendor/shopware/shopware/engine/Library/Enlight/Controller/Action.php(186): Shopware_Controllers_Frontend_Account->passwordAction() #13 /var/www/html/public/vendor/shopware/shopware/engine/Library/Enlight/Controller/Dispatcher/Default.php(467): Enlight_Controller_Action->dispatch() #14 /var/www/html/public/vendor/shopware/shopware/engine/Library/Enlight/Controller/Front.php(225): Enlight_Controller_Dispatcher_Default->dispatch() #15 /var/www/html/public/vendor/shopware/shopware/engine/Shopware/Kernel.php(197): Enlight_Controller_Front->dispatch() #16 /var/www/html/public/shopware.php(17): Shopware\Kernel->handle() #17 {main} thrown in /var/www/html/public/custom/project/SwagNewsletter/Subscriber/MailTransport.php on line 72`

### Expected behaviour

No Error is shown

### Steps to Reproduce?

Install SwagNewsletter Plugin and try to send password recovery Mail

**Comment by shyim** [comment]
Hey,

I have right now no time to maintain Shopware 5 plugins. Feel free to make a PR if you have already the fix :)
